[package]
name = "techno_bike"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evmap = "10.0.0"
evmap-derive = "0.2.0"
tiny_http = {git = "https://github.com/tobias1012/tiny-http.git"}
